// Global compile-time configuration for the intermittent-inference firmware.
//
// DEBUG  — binary switch (0/1).  When 1: assertions, per-sample accuracy,
//          testSPI, GPIO counters, and print helpers are compiled in.
//          Default 0 (production / release builds).
// VERBOSE — binary switch (0/1).  When 1: per-layer tensor dumps and
//          per-element matrix dumps are also compiled in.  Implies DEBUG.
//          Default 0.
//
// Both flags are set by the build system (Makefile or CMake), not here.
// The ifdefs below provide safe defaults so that files that include config.h
// without a prior -D definition compile correctly.
//
// ENABLE_DEMO_COUNTERS — when set, accumulates progress counters across power
//   cycles for demonstration purposes.  Mutually exclusive with
//   ENABLE_PER_LAYER_COUNTERS (see counters.h).

#pragma once

#define ENABLE_DEMO_COUNTERS 0

// Debug switches.
#ifndef DEBUG
#define DEBUG 0
#endif

#ifndef VERBOSE
#define VERBOSE 0
#endif

// VERBOSE implies DEBUG.
#if VERBOSE && !DEBUG
#undef DEBUG
#define DEBUG 1
#endif

// NVM backend selection.
// EXT_FRAM=1 (default for all targets): use the external SPI FRAM chip via
// extfram.h.
//   Supports any model up to the chip's capacity.
// EXT_FRAM=0: use the MSP430's internal FRAM as the NVM backend.
//   No SPI, no external chip.  Supports any model whose WRITABLE_NVM_SIZE
//   (generated by transform.py --internal-fram) fits in
//   the device's remaining internal FRAM after code and constants.
// Override at build time: make EXT_FRAM=1  (Makefile passes
// --define=EXT_FRAM=…)
#ifndef EXT_FRAM
#define EXT_FRAM 1
#endif
