// Accessors for the Node and NodeFlags arrays stored in NVM.
//
// nodes_data[] and node_orig_flags_data[] are generated by transform.py and
// compiled into data.cpp as flat byte arrays.  The get_node* / get_node_flags
// functions return typed pointers into those arrays — no deserialization copy.
//
// get_node(i) / get_node(param):
//   Returns a const pointer to the i-th Node, or the Node whose output is
//   param.  The param form uses parameter_info_idx to recover the node index.
//
// get_node_orig_flags(i):
//   Returns the compile-time-constant original flags from node_orig_flags_data.
//   These are never mutated at runtime; op handlers receive them as a read-only
//   reference to check initial configuration.
//
// get_node_flags(node_idx):
//   Returns a mutable pointer to the NodeFlags VM copy for this node.  The VM
//   copy is loaded from NVM on first access (detected via canary == 0) and
//   cached in SRAM for the rest of the power cycle.
//
// commit_node_flags(node_flags):
//   Writes the VM copy back to both NVM shadow copies (double-buffered write).
//   Only compiled in when VERBOSE or ENABLE_DEMO_COUNTERS,
//   because in production the flags are never modified at runtime.

#pragma once

#include <cstddef>
#include <cstdint>

#include "config.h"
#include "data.h"
#include "layer-defs.h"

struct Node;
struct NodeFlags;
struct ParameterInfo;

const Node* get_node(size_t i);
const NodeFlags* get_node_orig_flags(size_t i);
const Node* get_node(const ParameterInfo* param);

CurNodeFlags* get_node_flags(uint16_t node_idx);
#if VERBOSE || ENABLE_DEMO_COUNTERS
void commit_node_flags(const NodeFlags* node_flags);
#endif
