// Node and NodeFlags accessors: bridge between NVM model binary and runtime.
//
// nodes_data and node_orig_flags_data are generated byte arrays (from
// transform.py) that are copied into NVM at first_run().  At runtime, get_node
// and get_node_orig_flags simply cast into those arrays — no deserialization.
//
// NodeFlags mutability:
//   In production builds (!VERBOSE, no demo counters) the
//   per-node flags are never mutated during inference, so get_node_flags()
//   returns a pointer directly into the read-only node_orig_flags_data array.
//
//   In debug/demo-counter builds, flags may be written (e.g., cumulative_jobs
//   is updated).  get_node_flags() then uses a VM-side cache (node_flags_vm)
//   backed by shadow copies in NVM.  The canary field (0x55) distinguishes a
//   valid cached copy from an uninitialised struct — if it is zero the correct
//   copy is read from NVM.

#include "layers.h"

#include <cstddef>
#include <cstdint>

#include "cnn_common.h"
#include "config.h"
#include "data.h"
#include "data_structures.h"
#include "double_buffering.h"
#include "layer-defs.h"
#include "platform.h"

const Node* get_node(size_t i) {
  return reinterpret_cast<const Node*>(nodes_data) + i;
}

const NodeFlags* get_node_orig_flags(size_t i) {
  return reinterpret_cast<const NodeFlags*>(node_orig_flags_data) + i;
}

const Node* get_node(const ParameterInfo* param) {
  return get_node(param->parameter_info_idx - N_INPUT);
}

#if VERBOSE || ENABLE_DEMO_COUNTERS
NodeFlags node_flags_vm[MODEL_NODES_LEN];

template <>
uint32_t nvm_addr<NodeFlags>(uint8_t copy_id, uint16_t real_node_idx) {
  return NODE_FLAGS_OFFSET +
         (copy_id * MODEL_NODES_LEN + real_node_idx) * sizeof(NodeFlags);
}

template <>
NodeFlags* vm_addr<NodeFlags>(uint16_t real_node_idx) {
  return node_flags_vm + real_node_idx;
}

template <>
const char* datatype_name<NodeFlags>(void) {
  return "NodeFlags";
}

CurNodeFlags* get_node_flags(uint16_t node_idx) {
  NodeFlags* ret = node_flags_vm + node_idx;
  if (ret->canary != 0x55) {
    get_versioned_data<NodeFlags>(node_idx);
  }
  return ret;
}

void commit_node_flags(const NodeFlags* node_flags) {
  uint16_t node_idx = node_flags - node_flags_vm;
  commit_versioned_data<NodeFlags>(node_idx);
}

#else

CurNodeFlags* get_node_flags(uint16_t node_idx) {
  return get_node_orig_flags(node_idx);
}

#endif
