// Platform abstraction layer: NVM I/O, memory layout, and MCU-specific helpers.
//
// NVM LAYOUT (FRAM on MSP430/MSP432, simulated file on PC)
// =========================================================
// The NVM is split into two regions that grow toward each other:
//
//   Low addresses (growing up, heap-like):
//     [0,   16)                    reserved / SPI test area
//     [16,  256)                   LAST_REPORTED_LAYER_IDX
//     [256, 256+NUM_SLOTS*IVS)     intermediate activation slots (IVS each)
//     [... + SAMPLES_DATA_LEN)     input test-set samples
//     [... + PARAMETERS_DATA_LEN)  static model weights
//
//   High addresses (growing down, stack-like):
//     NVM_SIZE - INFERENCE_STATS_DATA_LEN   inference stats
//     - 2*MODEL_DATA_LEN                   Model (×2 shadow copies)
//     - INTERMEDIATE_PARAMETERS_INFO_DATA_LEN  ParameterInfo for each node
//     - NODE_FLAGS_DATA_LEN                NodeFlags (already ×2 in data)
//     - NODES_DATA_LEN                     Node descriptors
//     - FOOTPRINTS_DATA_LEN                HAWAII footprints (×2 shadow)
//     - COUNTERS_DATA_LEN                  performance counters
//     - INFERENCE_RESULTS_DATA_LEN         per-sample inference results
//
// The *_DATA_LEN constants and the model binary blobs (nodes_data,
// node_orig_flags_data, model_parameters_info_data, etc.) are generated by
// the Python transform script from an ONNX model and baked into data.h/data.c.

#pragma once

#include <cstdint>
#include <cstdlib>

#include "config.h"
#include "data.h"
#include "data_structures.h"

#if defined(__MSP430__) || defined(__MSP432__)
#include "plat-mcu.h"
#else
#include "plat-pc.h"
#endif

/* offsets for data on NVM */

// growing up (like heap). Not starting from zero as first few 16 bytes are for
// testing (see testSPI() function)
#define LAST_REPORTED_LAYER_IDX_OFFSET 16
#define INTERMEDIATE_VALUES_OFFSET 256
#define SAMPLES_OFFSET \
  (INTERMEDIATE_VALUES_OFFSET + NUM_SLOTS * INTERMEDIATE_VALUES_SIZE)
#define PARAMETERS_OFFSET (SAMPLES_OFFSET + SAMPLES_DATA_LEN)

// growing down (like stack)
#define INFERENCE_STATS_OFFSET (NVM_SIZE - INFERENCE_STATS_DATA_LEN)
#define MODEL_OFFSET (INFERENCE_STATS_OFFSET - 2 * MODEL_DATA_LEN)
#define INTERMEDIATE_PARAMETERS_INFO_OFFSET \
  (MODEL_OFFSET - INTERMEDIATE_PARAMETERS_INFO_DATA_LEN)
// Generated node_flags_data already contains two copies for shadowing, so there
// is no need to multiply the size by 2 here
#define NODE_FLAGS_OFFSET \
  (INTERMEDIATE_PARAMETERS_INFO_OFFSET - NODE_FLAGS_DATA_LEN)
#define NODES_OFFSET (NODE_FLAGS_OFFSET - NODES_DATA_LEN)
#define FOOTPRINTS_OFFSET (NODES_OFFSET - FOOTPRINTS_DATA_LEN)
#define COUNTERS_OFFSET (FOOTPRINTS_OFFSET - COUNTERS_DATA_LEN)
#define INFERENCE_RESULTS_OFFSET (COUNTERS_OFFSET - INFERENCE_RESULTS_DATA_LEN)

#ifdef __MSP432__
#define NOINIT [[gnu::section(".noinit")]]
#else
#define NOINIT
#endif

struct ParameterInfo;
struct Model;
struct Counters;
enum class GPIOFlag;
extern Model model_vm;

// put GPIOFlag here to make MSP-CGT LTO happy
enum class GPIOFlag {};

[[noreturn]] void ERROR_OCCURRED(void);
void read_from_nvm(void* vm_buffer, uint32_t nvm_offset, size_t n);
void write_to_nvm(const void* vm_buffer, uint32_t nvm_offset, size_t n,
                  uint16_t timer_delay = 0);
// DMA controller on MSP432 can handle at most 1024 words at a time
void read_from_nvm_segmented(uint8_t* vm_buffer, uint32_t nvm_offset,
                             uint32_t total_len, uint16_t segment_size);
void write_to_nvm_segmented(const uint8_t* vm_buffer, uint32_t nvm_offset,
                            uint32_t total_len, uint16_t segment_size = 1024);
void my_erase(void);
void copy_data_to_nvm(void);
void my_memcpy(void* dest, const void* src, size_t n);
void my_memcpy_to_param(ParameterInfo* param, uint32_t offset_in_word,
                        const void* src, size_t n, uint16_t timer_delay,
                        bool is_linear);
void my_memcpy_from_intermediate_values(void* dest, const ParameterInfo* param,
                                        uint32_t offset_in_word, size_t n);
// offset_in_bytes may go beyond 64K after being multiplied with sizeof(T)
void my_memcpy_from_parameters(void* dest, const ParameterInfo* param,
                               uint32_t offset_in_bytes, size_t n);
void read_from_samples(void* dest, uint32_t offset_in_word, size_t n);
ParameterInfo* get_intermediate_parameter_info(uint16_t i);
void commit_intermediate_parameter_info(const ParameterInfo* param);
void flush_intermediate_parameter_info();
Model* get_model(void);
Model* load_model_from_nvm(void);
void commit_model(void);
bool need_reset();
void first_run(void);
void notify_layer_finished(void);
void notify_model_finished(void);
void notify_indicator(uint8_t idx);
bool read_gpio_flag(GPIOFlag flag);
void save_model_output_data();
#if HAWAII

#if DYNAMIC_DNN_APPROACH == DYNAMIC_DNN_MULTIPLE_INDICATORS_BASIC || \
    DYNAMIC_DNN_APPROACH == DYNAMIC_DNN_MULTIPLE_INDICATORS
typedef _ExtendedFootprint Footprint;
struct UnshuffledFootprint {
  uint32_t values[3];
};
enum FootprintOffset {
  NUM_COMPLETED_JOBS = 0,
  COMPUTATION_UNIT_INDEX = 1,
  NUM_SKIPPED_JOBS = 2,
  NUM_FOOTPRINTS = 3,
};
void write_hawaii_layer_two_footprints(uint16_t layer_idx,
                                       FootprintOffset footprint_offset1,
                                       int16_t increment1,
                                       FootprintOffset footprint_offset2,
                                       int16_t increment2);
#else
typedef _Footprint Footprint;
struct UnshuffledFootprint {
  uint32_t values[1];
};
enum FootprintOffset {
  NUM_COMPLETED_JOBS = 0,
  NUM_FOOTPRINTS = 1,
};
#endif

extern UnshuffledFootprint unshuffled_footprint;
#if DYNAMIC_DNN_APPROACH == DYNAMIC_DNN_MULTIPLE_INDICATORS
extern UnshuffledFootprint unshuffled_footprint_mirror[2];
#endif
void unshuffle_footprint_values(const Footprint* footprint);
void write_hawaii_layer_footprint(uint16_t layer_idx, int16_t n_jobs);
void reset_hawaii_layer_footprint(uint16_t layer_idx);
void reset_footprint_copy_id_cache(void);
#endif
